# Generated by Django 5.0 on 2023-12-18 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Storeapp', '0002_shoppingcartitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.CharField(max_length=16)),
                ('card_owner', models.CharField(max_length=100)),
                ('cvv_code', models.CharField(max_length=4)),
                ('year_expiration', models.IntegerField()),
                ('month_expiration', models.IntegerField()),
            ],
        ),
    ]
